name: sunmi_print_ticket
description: This is a printer product written by cudev
homepage: https://github.com/hueht21/SunmiPrintEasyTicket


version: 1.0.7

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.example.easy_ticket_b08
        pluginClass: SunmiPrinterPlugin

